# App
spring.application.name=fraud-detection-engine
server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/paymentdb
spring.datasource.username=payment_user
spring.datasource.password=payment_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=fraud-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=com.fraud.kafka.event.TransactionEvent
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


# JWT
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Fraud Rules
fraud.rules.high-amount-threshold=50000
fraud.rules.velocity-limit=5
fraud.rules.velocity-window-seconds=60
fraud.rules.night-hour-start=1
fraud.rules.night-hour-end=4
fraud.rules.repeated-destination-limit=3

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
